name: Watch GitHub Releases

on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch: 

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run release watcher (mm.alexsyw.me)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          MATTERMOST_WEBHOOK: ${{ secrets.WEBHOOK_MM_ALEXSYW_ME }}
          REPOS_TO_WATCH: "netbirdio/netbird"
        run: python watchtower.py 

      - name: Run release watcher (mnbx)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          MATTERMOST_WEBHOOK: ${{ secrets.WEBHOOK_ZALOOP }}
          REPOS_TO_WATCH: "netbirdio/netbird"
        run: python watchtower.py 